name: fog-ros-baseimage

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/*'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/*'

jobs:
  build:
    name: fog-ros-baseimage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container metadata
        id: meta # referenced from later step
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/tiiuae/fog-ros-baseimage
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Container metadata for builder
        id: meta_builder # referenced from later step
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/tiiuae/fog-ros-baseimage
          tags: |
            type=ref,event=branch,prefix=builder-
            type=raw,value=builder-latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=sha,prefix=builder-

      - name: Build and push base image
        uses: docker/build-push-action@v2
        if: github.event_name == 'push'
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push builder
        uses: docker/build-push-action@v2
        if: github.event_name == 'push'
        with:
          push: true
          context: .
          file: Dockerfile.builder
          tags: ${{ steps.meta_builder.outputs.tags }}
          labels: ${{ steps.meta_builder.outputs.labels }}
